import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import postcss from "postcss";
import prefixSelector from "postcss-prefix-selector";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolve(packageRoot, "..");
const outputPath = join(packageRoot, "src", "styles", "template-editor.css");
const runtimeCssPath = join(
  sourceRoot,
  "client",
  "template-editor-runtime",
  "client",
  "template-editor-runtime",
  "template-editor-runtime.css",
);
const templateEditorCssPath = join(sourceRoot, "styles", "features", "template-editor.css");
const scopeSelector = ".examlist-template-editor";

function readUtf8(path) {
  return readFileSync(path, "utf8").replace(/^\uFEFF/, "");
}

if (!existsSync(runtimeCssPath) || !existsSync(templateEditorCssPath)) {
  if (existsSync(outputPath)) {
    console.log("Skipped CSS rebuild because the ExamList source tree is not available.");
    process.exit(0);
  }

  throw new Error("Could not find ExamList template editor CSS sources.");
}

function resolveCssImports(path, seen = new Set()) {
  const absolutePath = resolve(path);

  if (seen.has(absolutePath)) {
    return "";
  }

  seen.add(absolutePath);
  const source = readUtf8(absolutePath);
  const sourceDir = dirname(absolutePath);

  return source.replace(/@import\s+url\(["']?([^"')]+)["']?\);/g, (_match, importPath) => {
    const resolvedImportPath = resolve(sourceDir, importPath);

    if (!existsSync(resolvedImportPath) || extname(resolvedImportPath) !== ".css") {
      throw new Error(`Could not resolve CSS import ${importPath} from ${absolutePath}`);
    }

    return resolveCssImports(resolvedImportPath, seen);
  });
}

function shouldSkipSelector(selector) {
  const trimmedSelector = String(selector || "").trim();

  return !trimmedSelector || trimmedSelector.includes(scopeSelector);
}

const sourceCss = [
  "/* Runtime layout */",
  readUtf8(runtimeCssPath),
  "",
  "/* Template editor feature styles */",
  resolveCssImports(templateEditorCssPath),
].join("\n");

const result = await postcss([
  prefixSelector({
    prefix: scopeSelector,
    transform(_prefix, selector, prefixedSelector) {
      if (shouldSkipSelector(selector)) {
        return selector;
      }

      return prefixedSelector;
    },
  }),
]).process(sourceCss, {
  from: undefined,
});

const outputCss = [
  "/*",
  " * Generated by scripts/build-styles.js.",
  " * Import with: import \"examlist-template-editor/styles.css\";",
  " */",
  `${scopeSelector} {`,
  "  --ete-color-primary: #2563eb;",
  "  --ete-border-color: #d7dce5;",
  "  --ete-surface-background: #ffffff;",
  "  box-sizing: border-box;",
  "  color: var(--text-main, #142033);",
  "  font-family: var(--ete-font-family, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif);",
  "}",
  "",
  `${scopeSelector} *,`,
  `${scopeSelector} *::before,`,
  `${scopeSelector} *::after {`,
  "  box-sizing: border-box;",
  "}",
  "",
  result.css,
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, outputCss, "utf8");

console.log(`Built scoped template editor CSS at ${outputPath}.`);
