import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import postcss from "postcss";
import prefixSelector from "postcss-prefix-selector";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolve(packageRoot, "..");
const outputPath = join(packageRoot, "src", "styles", "template-editor.css");
const runtimeCssPath = join(
  sourceRoot,
  "client",
  "template-editor-runtime",
  "client",
  "template-editor-runtime",
  "template-editor-runtime.css",
);
const templateEditorCssPath = join(sourceRoot, "styles", "features", "template-editor.css");
const scopeSelector = ".examlist-template-editor";

function readUtf8(path) {
  return readFileSync(path, "utf8").replace(/^\uFEFF/, "");
}

if (!existsSync(runtimeCssPath) || !existsSync(templateEditorCssPath)) {
  if (existsSync(outputPath)) {
    console.log("Skipped CSS rebuild because the ExamList source tree is not available.");
    process.exit(0);
  }

  throw new Error("Could not find ExamList template editor CSS sources.");
}

function resolveCssImports(path, seen = new Set()) {
  const absolutePath = resolve(path);

  if (seen.has(absolutePath)) {
    return "";
  }

  seen.add(absolutePath);
  const source = readUtf8(absolutePath);
  const sourceDir = dirname(absolutePath);

  return source.replace(/@import\s+url\(["']?([^"')]+)["']?\);/g, (_match, importPath) => {
    const resolvedImportPath = resolve(sourceDir, importPath);

    if (!existsSync(resolvedImportPath) || extname(resolvedImportPath) !== ".css") {
      throw new Error(`Could not resolve CSS import ${importPath} from ${absolutePath}`);
    }

    return resolveCssImports(resolvedImportPath, seen);
  });
}

function shouldSkipSelector(selector) {
  const trimmedSelector = String(selector || "").trim();

  return !trimmedSelector || trimmedSelector.includes(scopeSelector);
}

const sourceCss = [
  "/* Runtime layout */",
  readUtf8(runtimeCssPath),
  "",
  "/* Template editor feature styles */",
  resolveCssImports(templateEditorCssPath),
].join("\n");

const result = await postcss([
  prefixSelector({
    prefix: scopeSelector,
    transform(_prefix, selector, prefixedSelector) {
      if (shouldSkipSelector(selector)) {
        return selector;
      }

      return prefixedSelector;
    },
  }),
]).process(sourceCss, {
  from: undefined,
});

const outputCss = [
  "/*",
  " * Generated by scripts/build-styles.js.",
  " * Import with: import \"examlist-template-editor/styles.css\";",
  " */",
  `${scopeSelector} {`,
  "  --ete-color-primary: #2563eb;",
  "  --ete-border-color: #d7dce5;",
  "  --ete-surface-background: #ffffff;",
  "  box-sizing: border-box;",
  "  color: var(--text-main, #142033);",
  "  font-family: var(--ete-font-family, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif);",
  "  overflow-x: auto;",
  "}",
  "",
  `${scopeSelector} *,`,
  `${scopeSelector} *::before,`,
  `${scopeSelector} *::after {`,
  "  box-sizing: border-box;",
  "}",
  "",
  `${scopeSelector} button,`,
  `${scopeSelector} input,`,
  `${scopeSelector} select,`,
  `${scopeSelector} textarea {`,
  "  color: inherit;",
  "  font: inherit;",
  "  letter-spacing: 0;",
  "  margin: 0;",
  "  min-width: 0;",
  "  text-transform: none;",
  "}",
  "",
  `${scopeSelector} button {`,
  "  -webkit-appearance: none;",
  "  appearance: none;",
  "  background: transparent;",
  "  border: 0;",
  "  cursor: pointer;",
  "  height: auto;",
  "  line-height: normal;",
  "  padding: 0;",
  "  width: auto;",
  "}",
  "",
  `${scopeSelector} button:disabled {`,
  "  cursor: not-allowed;",
  "}",
  "",
  result.css,
  "",
  "/* Package runtime layout compatibility */",
  `${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body {`,
  "  --editor-toolbar-column-width: 330px;",
  "  --editor-tag-column-width: 210px;",
  "  --editor-page-properties-column-width: 230px;",
  "  grid-template-columns:",
  "    var(--editor-toolbar-column-width)",
  "    var(--editor-tag-column-width)",
  "    var(--template-editor-canvas-panel-width, 818px)",
  "    var(--editor-page-properties-column-width);",
  "  grid-template-rows: minmax(0, 1fr);",
  "  min-width: max-content;",
  "  width: max-content;",
  "}",
  "",
  `${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body > .editor-toolbar-column {`,
  "  grid-column: 1;",
  "  grid-row: 1;",
  "}",
  "",
  `${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body > .template-tag-panel {`,
  "  grid-column: 2;",
  "  grid-row: 1;",
  "}",
  "",
  `${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body > .template-editor-page {`,
  "  grid-column: 3;",
  "  grid-row: 1;",
  "}",
  "",
  `${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body > .template-page-properties-panel {`,
  "  grid-column: 4;",
  "  grid-row: 1;",
  "}",
  "",
  "@media (max-width: 1120px) {",
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout {`,
  "    grid-template-columns: minmax(0, 1fr);",
  "    grid-template-rows: auto auto minmax(0, 1fr) auto;",
  "    min-width: 0;",
  "    width: 100%;",
  "  }",
  "",
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .editor-toolbar-column,`,
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .template-tag-panel,`,
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .template-editor-page,`,
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .template-page-properties-panel {`,
  "    grid-column: 1;",
  "    max-height: none;",
  "  }",
  "",
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .editor-toolbar-column {`,
  "    grid-row: 1;",
  "  }",
  "",
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .template-tag-panel {`,
  "    grid-row: 2;",
  "  }",
  "",
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .template-editor-page {`,
  "    grid-row: 3;",
  "    min-width: 0;",
  "  }",
  "",
  `  ${scopeSelector} .template-editor-runtime-shell.examlist-template-editor-body.is-responsive-layout > .template-page-properties-panel {`,
  "    grid-row: 4;",
  "    height: auto;",
  "  }",
  "}",
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, outputCss, "utf8");

console.log(`Built scoped template editor CSS at ${outputPath}.`);
